### ISSUE TITLE
Custom Servers

### ISSUE THREAD

**Issue by Mr-Fluuff** [DaemonBeast/Unify#2]
Allow a config file to connect to Custom Servers on custom IP instead of localhost. This would be a huge improvement

**Comment by DaemonBeast** [comment]
@MrF1uff I have been planning to do this and will definitely do it soon.

What I'm not so sure about is whether I should use a normal BepInEx `.cfg` config file or if I should use JSON. I don't want to use the normal `.cfg` config file because it will limit how many servers can be added, whereas JSON can be modified to add as many servers as you want.

I'll probably make it use a `.cfg` config file and then later change it to use a JSON file.

**Comment by Mr-Fluuff** [comment]
I think a config file would work for now because people like me need if for a closed group of friends when adding more mods and we only play mods with each other. Simple is I believe the way to go for now. Thank you in advance for responding so quickly

**Comment by DaemonBeast** [comment]
My pleasure. I'll be sure to add the feature as soon as I can.

**Comment by DaemonBeast** [comment]
@MrF1uff I've updated the code to allow you to add custom regions. The configuration instructions are located at the bottom of the README. I hope you enjoy! Also, if there are any issues or things that you think I should change, I would be very happy to hear them.

**Comment by DaemonBeast** [comment]
I'm also going to leave this issue open for now until I modify the code to use a JSON file to manage custom regions instead.
