### ISSUE TITLE
Region resets to North America on game end

### ISSUE THREAD

**Issue by neomis** [DaemonBeast/Unify#22]
The 4.0.0-pre release doesn't remember the region that's selected.  I know this isn't an official release so this is more of a FYI

**Comment by neomis** [comment]
Nevermind.  It was due to conflicts with TheOtherRoles

**Comment by DaemonBeast** [comment]
@neomis Is it an issue with TheOtherRoles? I've been experiencing it as well. However, it does "remember" it. It just doesn't display properly under the region menu button.

**Comment by DaemonBeast** [comment]
@neomis This is what I was going to say before you closed the issue:

The region is remembered as far as I know. It just seems to "reset" back to North America, but testing on my end has proven that it does remember what you chose and just displays North America instead for whatever reason.

I'm pushing an official update with Reactor and the issue seems to still persist (as I would expect). I'm currently looking into a solution to fix this.

**Edit:** I experience this when changing to any other menu then changing back or when a connection error is displayed. I haven't tested when leaving a game yet.

**Comment by DaemonBeast** [comment]
It seems your issue was linked to #24. I haven't tried using Unify with TheOtherRoles yet. I'll see what I can do to fix the conflict.

**Comment by DaemonBeast** [comment]
It seems the issue I was referring to is being fixed in this Reactor pull request: https://github.com/NuclearPowered/Reactor/pull/27.
